apiVersion: v1
kind: Service
metadata:
  name: multistate-api
  labels:
    app.kubernetes.io/name: multistate-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: multistate-api
